### ISSUE TITLE
Re-activate top-100 from #10538

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#10545]
#10536 #10538 I cannot do this all myself. Please mark this as a Good Volunteer Work. Thanks!

### top-100
 - [x] ./https-everywhere/rules/Adobe.xml #10597 
 - [x] ./https-everywhere/rules/Alipay.com.xml #10547 
 - [x] ./https-everywhere/rules/Apple.com.xml #10600 
 - [x] ./https-everywhere/rules/BBC.xml #10623 
 - [x] ./https-everywhere/rules/Facebook.xml #10567 
 - [x] ./https-everywhere/rules/Instagram.xml #10569 
 - [x] ./https-everywhere/rules/LinkedIn.xml #10624 
 - [x] ./https-everywhere/rules/Live.xml 10625
 - [x] ./https-everywhere/rules/Mail.ru.xml #10626 
 - [x] ./https-everywhere/rules/PayPal.xml #10566 
 - [x] ./https-everywhere/rules/Pinterest.xml #10548 
 - [x] ./https-everywhere/rules/PopAds.xml #10570 
 - [x] ./https-everywhere/rules/ThePirateBay.xml #10549 
 - [x] ./https-everywhere/rules/Tumblr.xml #10550 
 - [x] ./https-everywhere/rules/Twitch.tv.xml #10568 
 - [x] ./https-everywhere/rules/Yahoo.xml #10627 
 - [x] ./https-everywhere/rules/Yahoo_Japan.xml #9955 
 - [x] ./https-everywhere/rules/YouTube.xml #10564 
 - [x] ./https-everywhere/rules/amazon.co.jp.xml #10546 
 - [x] ./https-everywhere/rules/hao123.com-mixedcontent.xml #10629

**Comment by Bisaloo** [comment]
`facebook.com` is preloaded. Proofs: 

- https://hstspreload.org/?domain=facebook.com
- https://securityheaders.io/?q=facebook.com&followRedirects=on

**Comment by Bisaloo** [comment]
[`paypal.com` is preloaded](https://hstspreload.org/?domain=paypal.com) as well but is [missing the `preload` header.](https://hstspreload.org/?domain=paypal.com)

**Comment by Hainish** [comment]
Note: the relevant HSTS files to be checked for inclusion are those in the browsers we support:

https://hg.mozilla.org/releases/mozilla-release/raw-file/FIREFOX_54_0_RELEASE/security/manager/ssl/nsSTSPreloadList.inc
https://hg.mozilla.org/releases/mozilla-aurora/raw-file/tip/security/manager/ssl/nsSTSPreloadList.inc
https://hg.mozilla.org/releases/mozilla-esr52/raw-file/FIREFOX_52_2_0esr_RELEASE/security/manager/ssl/nsSTSPreloadList.inc
https://chromium.googlesource.com/chromium/src.git/+/59.0.3071.109/net/http/transport_security_state_static.json?format=TEXT

**Comment by Bisaloo** [comment]
@Hainish, but ultimately, those lists are pulled from hstspreload.org, right ? There is simply a delay before domains are included in the lists you mention.

>  This form is used to submit domains for inclusion in Chrome's HTTP Strict Transport Security (HSTS) preload list. This is a list of sites that are hardcoded into Chrome as being HTTPS only.

> Most major browsers (Chrome, Firefox, Opera, Safari, IE 11 and Edge) also have HSTS preload lists based on the Chrome list. (See the HSTS compatibility matrix.) 

That's how I understand this at least. Please tell me if I am mistaken.

**Comment by Hainish** [comment]
The browsers are based on the Chrome list, yes.  But it may take a while before they are included in the browsers, so we don't want to remove the rules that are preloaded from the canonical source prematurely and leave them actually unprotected in the browsers.

**Comment by Hainish** [comment]
Also Mozilla has its own logic for removing preloaded domains, and it's often changing and not documented very well.  So we can't count on the Mozilla implementation mirroring the Chrome list very closely.

**Comment by cschanaj** [comment]
I've just found out that [`Yahoo.xml`](https://github.com/cschanaj/https-everywhere/blob/master/src/chrome/content/rules/Yahoo.xml) was whitelisted in the `ruleset-coverage-whitelist.txt`. The file contain 2k+ lines and involves dozens of complicated rules, I don't think that anyone can re-activate it before the next release without significant effort ...

**Comment by Bisaloo** [comment]
> I've just found out that Yahoo.xml was whitelisted in the ruleset-coverage-whitelist.txt. The file contain 2k+ lines and involves dozens of complicated rules, I don't think that anyone can re-activate it before the next release without significant effort ...

Agreed. This is why we should keep different domains in separate rulesets. Updating behemoths such as `Yahoo.xml` is no fun and this leaves all domains unprotected.

**Comment by cschanaj** [comment]
If nobody can re-activate `Yahoo.xml` before the next release, I suggest to revert the changes from 9bf49cbeb4696cdea76df23f685da1d11031f693 on `Yahoo.xml` and whitelist it again. 

Remark: original file prior to the comprehensive-fetch [`Yahoo.xml`](https://github.com/EFForg/https-everywhere/blob/3d21c7109723060e6260cc81f357ae9c67992458/src/chrome/content/rules/Yahoo.xml)

**Comment by Hainish** [comment]
It seems like at the very least we should remove the problematic domains flagged by the fetch test, even if we don't have time to go through the entire rule and simplify it.

**Comment by Hainish** [comment]
Closing, since this seems to be done now.

**Comment by J0WI** [comment]
Thanks!
