### ISSUE TITLE
Re-activate top-1k from #10538

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#10782]
#10538 Noted that this is not as urgent as #10545 .

### top-1k 

- [x] ~./https-everywhere/rules/Automatic_Data_Processing.xml~
- [x] ./https-everywhere/rules/Lowes.com.xml #10893 
- [x] ./https-everywhere/rules/ASUS.xml #10789 
- [x] ./https-everywhere/rules/LinkedIn.xml #10624 
- [x] ./https-everywhere/rules/Live.xml #10625 
- [x] ./https-everywhere/rules/Mail.ru.xml #10626 
- [x] ./https-everywhere/rules/104.com.tw.xml #10787 
- [x] ./https-everywhere/rules/1688.com.xml #10854 
- [x] ./https-everywhere/rules/4Shared.xml #10788 
- [x] ./https-everywhere/rules/9gag.com.xml #10540 
- [x] ./https-everywhere/rules/Alibaba.xml #10651 
- [x] ./https-everywhere/rules/Apache.xml #10778 
- [x] ./https-everywhere/rules/Asana.xml #10650 
- [x] ./https-everywhere/rules/Blastingnews.com.xml #10798 
- [x] ./https-everywhere/rules/Booking.com.xml #10799 
- [x] ./https-everywhere/rules/Box.xml #10806 
- [x] ./https-everywhere/rules/BuzzFeed.xml #10818 
- [x] ./https-everywhere/rules/CapitalOne.com.xml #10855 
- [x] ./https-everywhere/rules/Cisco.xml #10856 
- [x] ./https-everywhere/rules/CodePen.io.xml #10815 
- [x] ./https-everywhere/rules/Doublepimp.xml #10780 
- [x] ./https-everywhere/rules/Dell.xml #10829 
- [x] ./https-everywhere/rules/Delta.com.xml #9877 
- [x] ./https-everywhere/rules/Douban.com.xml #10827 
- [x] ./https-everywhere/rules/DuckDuckGo.xml #10586 
- [x] ~./https-everywhere/rules/Electronic-Arts.xml~
- [x] ./https-everywhere/rules/Evernote.xml #10781 
- [x] ./https-everywhere/rules/Exoclick.xml #10824 
- [x] ./https-everywhere/rules/Expedia.xml #10831 
- [x] ./https-everywhere/rules/Flickr.xml #10610 
- [x] ./https-everywhere/rules/Focus.de.xml #10832 
- [x] ./https-everywhere/rules/Forbes.com.xml #10833 
- [x] ./https-everywhere/rules/GameSpot.xml #10834 
- [x] ./https-everywhere/rules/Glassdoor.xml #10835 
- [x] ./https-everywhere/rules/GoDaddy.xml #10857 
- [x] ./https-everywhere/rules/Groupon.com.xml #10836 
- [x] ./https-everywhere/rules/Hotels.com.xml #10837 
- [x] ./https-everywhere/rules/HubSpot.xml #10797 
- [x] ./https-everywhere/rules/IBM.xml #10795 
- [x] ./https-everywhere/rules/Ikea.com.xml #10794 
- [x] ./https-everywhere/rules/Intel.xml #10793 
- [x] ./https-everywhere/rules/Java.xml #10620 
- [x] ./https-everywhere/rules/Khan-Academy.xml #10792 
- [ ] ./https-everywhere/rules/LaPatilla.com.xml #10791 
- [x] ./https-everywhere/rules/League_of_Legends.com.xml #10790

**Comment by koops76** [comment]
@cschanaj ./https-everywhere/rules/Electronic-Arts.xml is not disabled.

**Comment by cschanaj** [comment]
@koops76 noted with thanks! 

P.S. do you mind to fix the Travis error in #10836, #10795 and #10794 before further working on this issues?

**Comment by koops76** [comment]
@cschanaj Done.

**Comment by koops76** [comment]
@cschanaj Maybe you should create a top-10k issue too?

**Comment by cschanaj** [comment]
@koops76 I would like to wait until #10545 and this PRs are closed.

**Comment by cschanaj** [comment]
hopefully #10888

**Comment by cschanaj** [comment]
@J0WI do you mind to have a review on #10791 such that I can close this issues?

**Comment by gloomy-ghost** [comment]
Thanks for these PR. They are all merged now, let's close this issue 😄
