### ISSUE TITLE
Spliting Wyndham.xml into Separate Rulesets

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#12672]
Type: other

The goal is to remove the wildcard `targets` and simplify this ruleset,

Part of #11203, [`Wyndham.xml`](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Wyndham.xml), [`Wyndham-mismatches.xml`](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Wyndham-mismatches.xml)

- [x] CanvasHolidays.co.uk (#12655)
- [x] Cheznous.com (#12673) 
- [x] CompetitionsByWyndham.com.au #13974 
- [x] Cottages.com (#13067)
- [x] Cottageselection.co.uk #13849 [REMOVED]
- [x] Cottagesdirect.co.uk (#14351)
- [x] English-Country-Cottages.co.uk (#13837)
- [x] EasyCottages.com (#12678) [REMOVED]
- [x] French-Country-Cottages.co.uk (#13758)
- [x] Hoseasons.co.uk (#12657)  
- [x] Individual-villas.co.uk (#13958) [REMOVED]
- [x] Irish-Country-Cottages.co.uk (#13371)
- [x] Italian-Country-Cottages.co.uk (#13837)
- [x] JamesVillas.co.uk (#12795)
- [x] Ovscruise.com (#13373)
- [x] RCI.com (#14507)
- [x] RCITravelStore.co.uk (#12656)
- [x] Resortquestsecure.com (#13850) [REMOVED]
- [x] Secureholidays.com (#14059) [REMOVED]
- [x] WelcomeCottages.com (#13996)
- [x] WyndhamJobs.com (#13382)
- [x] WyndhamVacationRentals.com (#14459)
- [x] Wyndhamvrap.com (#13375)
- [x] Landal.* (#13851)
- [x] Landalparkshop.de (#13838) 
- [x] Landalskilife.* (#13570)
- [x] LandalCampings.de (#13759)
- [x] Mijnlandal.nl (#13957) [REMOVED]
- [x] _Wyndham-mismatches.xml_ (#14064) [REMOVED]

**Comment by Bisaloo** [comment]
Related: https://github.com/EFForg/https-everywhere/issues/12297
