### ISSUE TITLE
Re-activate *.gov.uk from #12677

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#12886]
Type: ruleset issue

Domain: gov.uk

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

A number of *.gov.uk ruleset from #12677 can be re-activated.

P.S. If possible, please help to remove the comment from the bot. thanks!!

- [x] Aberdeenshire.gov.uk.xml (#12884)
- [x] ashford.gov.uk.xml (#13651)
- [x] aylesburyvaledc.gov.uk.xml (#14167)
- [x] barnsley.gov.uk.xml (#12952)
- [x] Business_Link.gov.uk.xml (#12892)
- [ ] cardiff.gov.uk.xml
- [x] Colchester.gov.uk.xml (#12887)
- [x] communities.gov.uk.xml (#12953)
- [x] cotswold.gov.uk.xml (#13485)
- [ ] decc.gov.uk.xml
- [x] Derby.gov.uk.xml (#12900)
- [x] Devon.gov.uk.xml (#12891)
- [ ] Doncaster.gov.uk.xml
- [x] East_Lothian.gov.uk.xml (#12954)
- [x] eastsussex.gov.uk.xml (#13539)
- [x] Falkirk.gov.uk.xml (#12899)
- [x] FSA.gov.uk.xml (#13484)
- [x] Glasgow.gov.uk.xml (#12955)
- [x] Gloucestershire.gov.uk.xml (#13478)
- [x] Havering.gov.uk.xml (#13649)
- [x] Herefordshire.gov.uk.xml (#13377)
- [x] HMRC.gov.uk.xml (#13479)
- [x] hscic.gov.uk.xml (#13073)
- [ ] lancashire.gov.uk.xml
- [x] leeds.gov.uk.xml  #(#13483)
- [x] London.gov.uk.xml (#12862)
- [x] MetOffice.gov.uk.xml (#13098)
- [x] maldon.gov.uk.xml (#14220)
- [x] Newcastle.gov.uk.xml (#13477)
- [ ] ofsted.gov.uk.xml
- [ ] orr.gov.uk.xml
- [x] portsmouth.gov.uk.xml (#13544)
- [x] Redbridge.gov.uk.xml (#13378)
- [x] runnymede.gov.uk.xml (#13074)
- [x] salford.gov.uk.xml (#13540)
- [x] scotland.gov.uk.xml (#13760)
- [x] shropshire.gov.uk.xml (#13648)
- [x] Southend.gov.uk.xml (#12885)
- [x] southribble.gov.uk (#13094)
- [x] stalbans.gov.uk.xml (#13075)
- [x] statistics.gov.uk.xml (#12888)
- [x] stockport.gov.uk.xml (#14221)
- [x] swale.gov.uk.xml (#13761)
- [x] Taunton_Deane.gov.uk.xml (#12957)
- [x] tunbridgewells.gov.uk.xml (#13486)
- [ ] wao.gov.uk.xml
- [x] West_Sussex.gov.uk.xml (#12898)
- [ ] worcestershire.gov.uk.xml
