### ISSUE TITLE
Audit default_off="self-signed" rulesets.

### ISSUE THREAD

**Issue by bardiharborow** [EFForg/https-everywhere#13091]
Type: other

The following `default_off="self-signed"` rulesets pass a `curl -I https://host/` scan for at least one host ([full host list](https://gist.github.com/bardiharborow/8cfb01eb478d7123eb0face869929b36)).

Fails fetch test (needs manual review):

- [x] [Channelx.biz.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Channelx.biz.xml) (#13126)
- [x] [Creative_Virtual.com.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Creative_Virtual.com.xml) (#13135)
- [x] [Digital-Transactions.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Digital-Transactions.xml) (#13136)
- [x] [Files.poulsander.com.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Files.poulsander.com.xml) (#13138)
- [x] [How_to_Box.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/How_to_Box.xml) (#13137)
- [x] [Macmillan.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Macmillan.xml) (#13091)
- [x] [MegaStock.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/MegaStock.xml) (#13174)
- [x] [PCS.com.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/PCS.com.xml) (#13139)
- [x] [PL-Casual-Dating.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/PL-Casual-Dating.xml) (#13175)
- [x] [Racket-lang.org.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Racket-lang.org.xml) (#13140)
- [x] ~~[WebUrbanist.com.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/WebUrbanist.com.xml)~~ (redirects to http)

`-problematic` rulesets that need merging with their main rulesets:

- [x] [ChannelAdvisor.com-problematic.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/ChannelAdvisor.com-problematic.xml) (#13144)
- [x] [Holtwick-IT-mismatches.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Holtwick-IT-mismatches.xml) (#13141)
- [x] [Palm_Coast_Data-problematic.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Palm_Coast_Data-problematic.xml) (#13171)
- [x] [RCUK.ac.uk-problematic.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/RCUK.ac.uk-problematic.xml) (#13172)

Passes fetch test (possible bulk re-enabling):

- [x] [Ancud.de.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Ancud.de.xml) (#13145)
- [x] [Betanews.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Betanews.xml) (#13145)
- [x] [DENX.de.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/DENX.de.xml) (#13145)
- [x] [Drwho.virtadpt.net.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Drwho.virtadpt.net.xml) (#13145)
- [x] [Echothrust.com.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Echothrust.com.xml) (#13145)
- [x] [Engelschall.com.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Engelschall.com.xml) (#13145)
- [x] [EW-online.de.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/EW-online.de.xml) (#13145)
- [x] [Goddard-Group.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Goddard-Group.xml) (#13145)
- [x] [Huxo.co.uk.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Huxo.co.uk.xml) (#13145)
- [x] [IED-Industrieanlagen-und-Engineering.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/IED-Industrieanlagen-und-Engineering.xml) (#13145)
- [x] [Infile.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Infile.xml) (#13145)
- [x] [IWM_Network.com.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/IWM_Network.com.xml) (#13145)
- [x] [Jeja.pl.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Jeja.pl.xml) (#13145)
- [x] [JGuitar.com.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/JGuitar.com.xml) (#13145)
- [x] [Kanshoo.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Kanshoo.xml) (#13145)
- [x] [Kosimak.com.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Kosimak.com.xml) (#13145)
- [x] [Kovidgoyal.net.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Kovidgoyal.net.xml) (#13145)
- [x] [Krautchan.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Krautchan.xml) (#13145)
- [x] [Linkomanija.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Linkomanija.xml) (#13145)
- [x] [Merca20.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Merca20.xml) (#13145)
- [x] [Milwaukee-Makerspace.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Milwaukee-Makerspace.xml) (#13145)
- [x] [Praegnanz.de.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Praegnanz.de.xml) (#13145)
- [x] [Premier_Tax_Free.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Premier_Tax_Free.xml) (#13145)
- [x] [Resonant.org.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Resonant.org.xml) (#13095)
- [x] [SRA_OSS.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/SRA_OSS.xml) (#13145)
- [x] [Suburban-Records.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Suburban-Records.xml) (#13145)
- [x] ~~[Tr0n.net.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Tr0n.net.xml)~~ (preloaded)
- [x] [Tweegy.nl.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Tweegy.nl.xml) (#13145)
- [x] [United_Computer_Wizards.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/United_Computer_Wizards.xml) (#13145)
- [x] [Universe_2.us.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Universe_2.us.xml) (#13145)
- [x] [Vehicle_Visuals.com.xml](https://github.com/EFForg/https-everywhere/blob/4f045a2644e7281bd28d8641511a37fd13c7b695/src/chrome/content/rules/Vehicle_Visuals.com.xml) (#13145)

**Comment by Bisaloo** [comment]
Did you run HSTS-prune before making this list?

**Comment by bardiharborow** [comment]
@Bisaloo I did not but I can do so.

**Comment by bardiharborow** [comment]
@Bisaloo `tr0n.net` is preloaded. Everything else should be good.

**Comment by bardiharborow** [comment]
We're all done here. 😄
