### ISSUE TITLE
Audit default_off="expired" rulesets.

### ISSUE THREAD

**Issue by bardiharborow** [EFForg/https-everywhere#13176]
Type: other

The following `default_off="expired"` rulesets pass a `curl -I https://host/` scan for at least one host:

Fails fetch test (needs manual review):

- [ ] [AboutUs-problematic.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/AboutUs-problematic.xml)
- [ ] [CableTV.com.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/CableTV.com.xml)
- [x] [CloudFlare_Challenge.com.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/CloudFlare_Challenge.com.xml)
- [ ] [Etre_Touchy.com.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Etre_Touchy.com.xml)
- [ ] [EuroSmartz.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/EuroSmartz.xml)
- [ ] [Extabit.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Extabit.xml)
- [ ] [Media-Proweb.de.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Media-Proweb.de.xml)
- [ ] [Motigo.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Motigo.xml)
- [ ] [MyFreeCopyright.com-problematic.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/MyFreeCopyright.com-problematic.xml)
- [ ] [Npm.im.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Npm.im.xml)
- [ ] [Oyunhizmetleri.com.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Oyunhizmetleri.com.xml)
- [ ] [RTK.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/RTK.xml)
- [ ] [Silverflint.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Silverflint.xml)
- [ ] [ThunderRanch.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/ThunderRanch.xml)
- [ ] [UPI.com-falsemixed.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/UPI.com-falsemixed.xml)
- [ ] [UPI.com.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/UPI.com.xml)

`-problematic` rulesets that need merging with their main rulesets:

- [ ] [Easyspace-expired.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Easyspace-expired.xml)
- [ ] [Es.gy-problematic.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Es.gy-problematic.xml)
- [ ] [InkFrog.com-problematic.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/InkFrog.com-problematic.xml)
- [ ] [MoAF.org-problematic.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/MoAF.org-problematic.xml)
- [ ] [Netistrar.com-problematic.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Netistrar.com-problematic.xml)
- [ ] [OpenTTD-expired.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/OpenTTD-expired.xml)
- [ ] [OSR_Foundation.org-problematic.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/OSR_Foundation.org-problematic.xml)

Passes fetch test (possible bulk re-enabling):

- [x] [Adsurve.com.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Adsurve.com.xml) (#13177)
- [x] [Amnistia.cl.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Amnistia.cl.xml) (#13177)
- [x] [Boost.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Boost.xml) (#13177)
- [x] [BrightContext.com.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/BrightContext.com.xml) (#13177)
- [x] [Bufferbloat.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Bufferbloat.xml) (#13177)
- [x] [Cloudmining.guru.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Cloudmining.guru.xml) (#13177)
- [x] [CodingTeam.net.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/CodingTeam.net.xml) (#13177)
- [x] [Com-Sys.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Com-Sys.xml) (#13177)
- [x] [ConnectiCon.org.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/ConnectiCon.org.xml) (#13177)
- [x] [Crafty_Syntax.com.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Crafty_Syntax.com.xml) (#13177)
- [x] [Craphound.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Craphound.xml) (#13177)
- [x] [CrazyBump.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/CrazyBump.xml) (#13177)
- [x] [Digital_News_Agency.com.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Digital_News_Agency.com.xml) (#13177)
- [x] [Ferroh.com.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Ferroh.com.xml) (#13177)
- [x] [FileTrip.net.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/FileTrip.net.xml) (#13177)
- [x] [finseth.com.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/finseth.com.xml) (#13177)
- [x] [Grupo_Avante.org.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Grupo_Avante.org.xml) (#13177)
- [x] [Guillaume_Dargauds_website.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Guillaume_Dargauds_website.xml) (#13177)
- [x] [Healthfuze.com.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Healthfuze.com.xml) (#13177)
- [x] [Hotel_Managaby.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Hotel_Managaby.xml) (#13177)
- [x] [Kaiserslautern.de.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Kaiserslautern.de.xml) (#13177)
- [x] [Linux_Forums.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Linux_Forums.xml) (#13177)
- [x] [MOBIUS.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/MOBIUS.xml) (#13177)
- [x] [Orange_Static.com.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Orange_Static.com.xml) (#13177)
- [x] [Papakaya.com.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Papakaya.com.xml) (#13177)
- [x] [Scott-Hanselman.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Scott-Hanselman.xml) (#13177)
- [x] [Sears_Labs.com.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Sears_Labs.com.xml) (#13177)
- [x] [SmartHide.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/SmartHide.xml) (#13177)
- [x] [Social_Fixer.com.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Social_Fixer.com.xml) (#13177)
- [x] [SourceMaking.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/SourceMaking.xml) (#13177)
- [x] [Spankwire.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Spankwire.xml) (#13177)
- [x] [Spectator.org.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Spectator.org.xml) (#13177)
- [x] [Stop_Software_Patents.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/Stop_Software_Patents.xml) (#13177)
- [x] [The_Internet_Co.net.xml](https://github.com/EFForg/https-everywhere/blob/0279990170739dc8c3e9d8cace9e2d4065898a85/src/chrome/content/rules/The_Internet_Co.net.xml) (#13177)

Rerun:

AboutUs-problematic.xml
BeastNode-problematic.xml
Bitcoin_Plus.xml
CableTV.com.xml
CloudForge.xml
Evisa-Vietnam.Com.xml
Extabit.xml
IOCCC.org.xml
ImpSec.org.xml
InkFrog.com-problematic.xml
Matomy-Media.xml
MonkeyGuts.com.xml
MyFreeCopyright.com-problematic.xml
Netdev01.org.xml
Netistrar.com-problematic.xml
Npm.im.xml
Omar_and_Will.com.xml
Oyunhizmetleri.com.xml
RTK.xml
Sickbits.net.xml
Xplr.xml
