### ISSUE TITLE
Clean ups for after transition to webextensions

### ISSUE THREAD

**Issue by cowlicks** [EFForg/https-everywhere#13205]
Type: code issue

- [ ] move rulesets, see #7649 
- [ ] update/move translations, see #13203
- [ ] streamline build process, see #13190 

I'll be editing this to add new items.

**Comment by koops76** [comment]
@cowlicks move rulesets into a separate repo.*
