### ISSUE TITLE
Audit default_off="missing certificate chain" rulesets.

### ISSUE THREAD

**Issue by bardiharborow** [EFForg/https-everywhere#13290]
Type: other

The following `default_off="missing certificate chain"` rulesets pass the fetch test:

`-problematic` rulesets that need merging with their main rulesets:

- [ ] [Modernrepo.com-problematic.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Modernrepo.com-problematic.xml)
- [ ] [Moodle.net-problematic.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Moodle.net-problematic.xml)
- [ ] [North-Carolina-State-University-problematic.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/North-Carolina-State-University-problematic.xml)
- [ ] [Open_InfoSec_Foundation.org-problematic.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Open_InfoSec_Foundation.org-problematic.xml)
- [ ] [Os-cillation-mismatches.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Os-cillation-mismatches.xml)
- [ ] [ShareFile_support.com-problematic.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/ShareFile_support.com-problematic.xml)
- [ ] [UC_Hastings.edu-problematic.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/UC_Hastings.edu-problematic.xml)
- [ ] [VPS.net-problematic.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/VPS.net-problematic.xml)

Passes fetch test (possible bulk re-enabling):

- [ ] [accessedge.com.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/accessedge.com.xml)
- [x] [Advconversion.com.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Advconversion.com.xml) (#13677)
- [x] [Andrew_Brookins.com.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Andrew_Brookins.com.xml) (#13677)
- [x] [andrewmohawk.com.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/andrewmohawk.com.xml) (#13677)
- [x] [Ask_the_Builder.com.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Ask_the_Builder.com.xml) (#13677)
- [ ] [Be_Mobile.ua.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Be_Mobile.ua.xml)
- [x] [BitVisor.org.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/BitVisor.org.xml) (#13677)
- [x] [Blank_Slate.io.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Blank_Slate.io.xml) (#13677)
- [x] [Clkads.com.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Clkads.com.xml) (#13677)
- [ ] [CoGen-Media.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/CoGen-Media.xml)
- [x] [CQ_Roll_Call.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/CQ_Roll_Call.xml) (#13676)
- [x] [Dixcart.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Dixcart.xml) (#13677)
- [x] [East-Northamptonshire.gov.uk.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/East-Northamptonshire.gov.uk.xml) (#12954)
- [x] [Engaging_Networks.net.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Engaging_Networks.net.xml) (#13677)
- [x] [findip-address.com.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/findip-address.com.xml) (#13290)
- [x] [Flownative.com.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Flownative.com.xml) (#13677)
- [x] [Global_Network_Initiative.org.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Global_Network_Initiative.org.xml) (#13677)
- [x] [HKGov-AFCD.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/HKGov-AFCD.xml) (#13677)
- [x] [Immunityinc.com.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Immunityinc.com.xml) (#13677)
- [x] [Islenzka.net.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Islenzka.net.xml) (PR pending)
- [x] [jewishvirtuallibrary.org.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/jewishvirtuallibrary.org.xml) (#13677)
- [x] [link-page.info.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/link-page.info.xml) (#13677)
- [x] [London_Sock_Company.com.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/London_Sock_Company.com.xml) (#13677)
- [x] [Oberheide.org.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Oberheide.org.xml) (#13677)
- [x] [ox4.li.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/ox4.li.xml) (#13677)
- [x] [Pilgrimage_Software.com.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Pilgrimage_Software.com.xml) (#13677)
- [x] [pirata.cat.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/pirata.cat.xml)
- [x] [rbwmcarshare.co.uk.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/rbwmcarshare.co.uk.xml) (#13677)
- [x] [Renovation_Experts.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Renovation_Experts.xml) (#13677)
- [x] [Scalability.org.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Scalability.org.xml) (#13677)
- [x] [ScanMyServer.com.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/ScanMyServer.com.xml) (#13677)
- [x] [SecurityWeek.com.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/SecurityWeek.com.xml) (#15768)
- [ ] [SilverRush_Style.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/SilverRush_Style.xml)
- [x] [Srdrvp.com.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Srdrvp.com.xml) (#13677)
- [x] [SuperAntiSpyware.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/SuperAntiSpyware.xml) (#13677)
- [x] [Tb.cn.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Tb.cn.xml) (#13677)
- [ ] [Upickem.net.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Upickem.net.xml)
- [x] [US_Pirates.org.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/US_Pirates.org.xml) (#13677)
- [x] [Waag.org.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Waag.org.xml) (#13677)
- [x] [Webthumbnail.org.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Webthumbnail.org.xml) (#13677)
- [x] [xrllc.com.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/xrllc.com.xml) (#13677)
- [x] [YorkNY.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/YorkNY.xml) (#13677)
- [ ] [Zeusclicks.com.xml](https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/src/chrome/content/rules/Zeusclicks.com.xml)
