### ISSUE TITLE
Tracking bug for issue bot improvements

### ISSUE THREAD

**Issue by strugee** [EFForg/https-everywhere#14616]
Type: code issue

This is a tracking bug collecting all the ideas that have been proposed for the issue format bot, in various issues. Feel free to comment below and I'll edit the description to add ideas to the list.

Issues with high impact and low work factor are prioritized higher.

- [x] [PR #14617] Automatically report code coverage when the test suite is run
- [ ] Strip domain information when it doesn't make sense for the type
- [x] [PR #15439] Link to the issue template when posting error messages
- [x] [PR #15439] Adjust wording (https://github.com/EFForg/https-everywhere/issues/14654#issuecomment-366416388)
- [x] [PR #14698] Have the bot autolabel ruleset issues, code issues, etc. (https://github.com/EFForg/https-everywhere/issues/13890#issuecomment-364301461)
- [ ] Didn't label #15594 correctly
- [ ] Allow community members to ask the bot to label an issue as potentially outdated (not sure this is a good idea but would help people with write access find issues to close, see https://github.com/EFForg/https-everywhere/issues/13890#issuecomment-364202481)
- [ ] Allow community members to ask the bot to add metadata to the issue description (https://github.com/EFForg/https-everywhere/issues/13890#issuecomment-364301461)
- [x] [PR #14635] Update dependencies
- [ ] Debug the webhook signature crash (https://github.com/EFForg/https-everywhere/pull/11615#issuecomment-3606688490)
- [ ] Merge the PR labelling bot (https://github.com/EFForg/https-everywhere/pull/11615#issuecomment-360898571)
- [ ] Have the bot manage incoming ruleset ideas in a separate repository (https://github.com/EFForg/https-everywhere/issues/13890#issuecomment-3617661260)
- [ ] Reference other issues/PRs with shared domains (https://github.com/EFForg/https-everywhere/issues/14616#issuecomment-365190936)
- [ ] Investigate Probot 4.0's improved logging - https://github.com/probot/probot/releases/tag/v4.0.0
- [ ] Clean up the test suite (#13466)
- [ ] Have Travis CI run the bot test suite

**Comment by Bisaloo** [comment]
It would also be useful if the bot could warn the OP when there is another open issue/PR with the same domain.

It would:

- help prevent duplicates
- ensure contributors fix all issues related to a specific domain where they open a PR
- inform users that their issue may already be fixed in a pending PR
- ...

This may be tricky though because it would require the bot to keep a list of domains and to scan all issues/PR every single time.

**Comment by strugee** [comment]
@Bisaloo that's a good idea. However GitHub doesn't provide a good API for issues search, at least not in APIv3. I think we should be able to just load all the open issues in memory though, if we don't keep any of the issue bodies and basically just map domain -> issue number(s). I'll have to measure the memory consumption but I think it'll be okay - although what if the issue list grows? There are ~500 open issues as of this writing.

**Comment by Bisaloo** [comment]
> - Allow community members to ask the bot to label an issue as potentially outdated (not sure this is a good idea but would help people with write access find issues to close, see #13890 (comment))
> - Allow community members to ask the bot to add metadata to the issue description (#13890 (comment))

About this, I would like to be able to label:

- CORS issues
- MCB

Also, the bot should probably label all ruleset issues as such. Right now, we only know this because of Alexa ranks. And it only works if rank < 1M.

**Comment by strugee** [comment]
@Bisaloo see the second item in the list.

**Comment by pipboy96** [comment]
The bot seems to have been disabled.

**Comment by strugee** [comment]
Yeah, I'm curious what happened there? Did it fall over or were people not happy with the way it worked?

**Comment by pipboy96** [comment]
@strugee Mostly the fact it wasn't well written and created spam comments. I want to try to fix it if possible, so it could be restarted.

**Comment by Bisaloo** [comment]
@strugee, my understanding it that it fell over and nobody bothered restarting it. You'd need to ask @zoracon for more info.

@pipboy96, wasn't the multiple comment issue fixed? I don't remember very well

**Comment by strugee** [comment]
> Mostly the fact it wasn't well written and created spam comments. I want to try to fix it if possible, so it could be restarted.

If it was creating spam comments I wish someone would've pinged me so I could fix it. Unless you were referring to #13460? But that was fixed over a year and a half ago.
