### ISSUE TITLE
Trivialize complex rewrites to Cloudfront.net

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#15970]
There exists a number of complex rules which rewrites to `cloudfront.net`, it seems that a number of them is no longer necessary (with a trivial `curl -I` test to HTTPS)

- [ ] cdn1.360cities.net (#15971)
- [ ] cdn2.360cities.net (#15971)
- [ ] cdn1.aoe.com (#15972)
- [ ] cdn2.aoe.com (#15972)
- [ ] binaryapi.ap.org (#15976)
- [ ] file2.engineering.com (#15973)
- [ ] cdn.leagueoflegends.com (#15975) 
- [ ] marsstaticcdn.jpl.nasa.gov (#15974)
- [ ] assets.vice.com (#15945)
- [x] cdn.adk2.com
- [x] files.adspdbl.com
- [x] cdn.altex.ro
- [x] c.cksource.com
- [ ] cdnd.cosmosmagazine.com
- [x] imagelib4.circleofmoms.com
- [x] images3.circleofmoms.com
- [x] media.cmcdn.net
- [x] support.comixology.com
- [x] cnda.condenast.co.uk
- [x] imageservice.customersaas.com
- [x] static1.customersaas.com
- [x] s.cxt.ms
- [x] cdn-static.dealerrater.com
- [x] cdn-user.dealerrater.com
- [x] webassets.desk.com
- [x] four.cdn.directmailmac.com
- [x] a1.divshot.com
- [x] news-cdn.efinancialcareers.com
- [x] cimg.filemobile.com
- [x] static.thefullsignal.com
- [x] cfs1.gcaptain.com
- [x] c.gumgum.com
- [x] demo.idg.com.au
- [x] userimages.ittoolbox.com
- [x] 2.imimg.com
- [x] 3.imimg.com
- [x] 4.imimg.com
- [x] im.gifbt.com
- [x] imgs.inkfrog.com
- [ ] content.internetvideoarchive.com
- [ ] static.iono.fm
- [ ] content.jawbone.com
- [ ] cdn.lesfurets.com
- [ ] cdn.lrb.co.uk
- [ ] cdn.thinksteroids.com
- [ ] downloads.mailchimp.com
- [ ] up.massrelevance.com
- [ ] cloudfront.mediamatters.org
- [ ] download2.mikrotik.com
- [ ] cdn3.minted.com
- [ ] cdn4.minted.com
- [ ] cdn5.minted.com
- [ ] vid.mobypicture.com
- [ ] media.nostarch.com
- [ ] ap1.pbase.com
- [ ] files.pcbooster.com
- [ ] assets1.prx.org
- [ ] images.psxextreme.com
- [ ] s1.pir.fm
- [ ] download.piriform.com
- [ ] images.resellerratings.com
- [ ] assets.rightscale.com
- [ ] assets-production.rovio.com
- [ ] cdn.smfboards.com
- [ ] media.sailthru.com
- [ ] img.scoop.it
- [ ] static.shareasale.com
- [ ] media1.shmoop.com
- [ ] media.showcase.ca
- [ ] static.smdg.ca
- [ ] images.sodahead.com
- [ ] assets.sussan.com.au
- [ ] img.lightreading.com
- [ ] sd.thejournal.ie
- [ ] assets.theresumator.com
- [ ] cdn.thesn.net
- [ ] assets.trialpay.com
- [ ] sitefiles.turbosquid.com
- [ ] staticd.vsco.co
- [ ] cf.cdn.vid.ly
- [ ] s.vid.ly
- [ ] cache.visitestonia.com
- [ ] files.tested.com
- [ ] cdn.xignite.com
- [ ] static.zdbb.net
- [ ] sd.jrnl.ie
- [ ] img.lightreading.com
- [ ] media.scmagazine.com

**Comment by cschanaj** [comment]
Note: a number of cloudfront.net rewrites has been trivialized in #15998
