### ISSUE TITLE
Fix or close PRs with invalid XML

### ISSUE THREAD

**Issue by pipboy96** [EFForg/https-everywhere#17277]
cc @Bisaloo @J0WI
- [x] #14978 (`--` inside a comment)
- [x] #14785 (broken closing tag, author is @ghost)
- [x] #13857 (broken closing tag)
- [x] #15210 (typo in target host)
