### ISSUE TITLE
Technical Documentation Needs for HTTPS Everywhere

### ISSUE THREAD

**Issue by zoracon** [EFForg/https-everywhere#17820]
Type: other

### Repo docs
- [x] Split documentation into three categories #14579
- [x] Readme compliance with Google Markdown Style #17547
- [x] Review `/docs` directory to make sure `.md` files are up to date
- [x] Consolidate Testing docs into one wiki page (various ReadMe docs in repo, would be nice to have one wiki page to refer to)
Examples: 
- https://github.com/EFForg/https-everywhere/blob/master/utils/create-platform-certs/README.md
- https://github.com/EFForg/https-everywhere/blob/master/utils/issue-format-bot/README.md
- https://github.com/EFForg/https-everywhere/blob/master/test/README.md
- [x] Tweak wording on FAQ page https://github.com/EFForg/https-everywhere/pull/19571#pullrequestreview-485938813
- [x]  Consolidate and update HTTPSE Page Docs #14565

### [FAQ](https://www.eff.org/https-everywhere/faq) updates
Questions that need updates
- [x] ["How do I get rid of/move the HTTPS Everywhere button in the toolbar?"](https://www.eff.org/https-everywhere/faq#how-do-i-get-rid-ofmove-the-https-everywhere-button-in-the-toolbar)
- [x] ["When does HTTPS Everywhere protect me? When does it not protect me?"](https://www.eff.org/https-everywhere/faq#when-does-https-everywhere-protect-me-when-does-it-not-protect-me)
- [x] ["What do the different colors for rulesets in the Firefox toolbar menu mean?"](https://www.eff.org/https-everywhere/faq#what-do-the-different-colors-for-rulesets-in-the-firefox-toolbar-menu-mean)

**Comment by pipboy96** [comment]
Unlocked just to add :+1:.

**Comment by cschanaj** [comment]
IMHO, it might worth to incorporate the suggestions in #14579 for better organization of the new documentations. For the FAQ updates, EFF might want to address these outstanding issues: #2088, #7282, #7936, #9466, #9467, #13817.

AFAIK, the HTTPSE works a bit differently on each supported browsers, regarding the mixed content, platform specific features like #15157 and bugs like #16394. It would be great if there is a section in the documentation acknowledging the differences.

**Comment by pipboy96** [comment]
I would like to work on 1 (Readme compliance with Google Markdown Style).

**Comment by zoracon** [comment]
> I would like to work on 1 (Readme compliance with Google Markdown Style).

Feel free to work on it! Thank you

**Comment by cschanaj** [comment]
In the FAQ, EFF might also want to explain the difference between HTTPS Everywhere and the HTTPS-Only Mode in Firefox 83.

**Comment by zoracon** [comment]
> In the FAQ, EFF might also want to explain the difference between HTTPS Everywhere and the HTTPS-Only Mode in Firefox 83.
Done! https://www.eff.org/https-everywhere/faq#https-only-mode
