### ISSUE TITLE
Rulesets that rewrite to s3.amazonaws.com will break in September 2020

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#17912]
## Remaining rulesets

- [x] Issuu_Aps.xml
- [x] FeedBlitz.xml
- [x] DaWanda.xml
- [x] Filemobile.xml
- [x] Compendium.xml
- [x] Smowtion.xml
- [x] SMF_for_Free.xml
- [x] Scribd.com.xml
- [x] SBNdev.net.xml
- [x] JanRain.xml
- [x] Roster-Teeth.xml
- [x] Wishabi.xml
- [x] IPR_Software.com.xml (default_off)
- [x] Intuit.xml (default_off)
- [x] PR-Newswire.xml (default_off)

### Awaiting merge

- [x] Quizsnack.com.xml (#19580)
- [x] RPXNow.com.xml (#19581)
- [x] KIXEYE.xml (#19583)
- [x] GEBlogs.com.xml (#19584)

## Original issue comment

Per https://forums.aws.amazon.com/ann.jspa?annID=6776,

> Amazon S3 currently supports two request URI styles in all regions: path-style (also known as V1) that includes bucket name in the path of the URI (example: //s3.amazonaws.com/<bucketname>/key), and virtual-hosted style (also known as V2) which uses the bucket name as part of the domain name (example: //<bucketname>.s3.amazonaws.com/key). In our effort to continuously improve customer experience, the path-style naming convention is being retired in favor of virtual-hosted style request format. Customers should update their applications to use the virtual-hosted style request format when making S3 API requests before September 30th, 2020 to avoid any service disruptions. Customers using the AWS SDK can upgrade to the most recent version of the SDK to ensure their applications are using the virtual-hosted style request format. 

In other words, all rulesets that have a `to=` using the s3.amazonaws.com hostname will stop working. We should update all of these before then. Here's the current list of 115 affected rulesets:

```
$ grep to=.*s3.amazonaws.com src/chrome/content/rules/*
3D_Vision_Live.com.xml:		to="https://s3.amazonaws.com/photos.3dvisionlive/$2/images/$1/cached.thumb.square.208.208.0.0" /-->
AboutUs.xml:		to="https://s3.amazonaws.com/au-site-static-assets/" />
ActBlue.xml:		to="https://s3.amazonaws.com/i.actblue.com/" />
AdExcite.xml:		to="https://adexcite.s3.amazonaws.com/" />
AdExtent.com.xml:		to="https://s3.amazonaws.com/appv2.adextent.com/" />
Adobe.xml:		to="https://s3.amazonaws.com/images.groups.adobe.com/" />
Alonetone.xml:		to="https://s3.amazonaws.com/stash.alonetone.com/" />
AmazonAWS.com.xml:		to="https://s3.amazonaws.com/static.newsblur.com/" />
AmazonAWS.com.xml:		to="https://$1.s3.amazonaws.com/" /-->
AmazonAWS.com.xml:		to="https://s3.amazonaws.com/$1.$2/" /-->
AmazonAWS.com.xml:		to="https://s3.amazonaws.com/" />
AWeber.xml:		to="https://s3.amazonaws.com/hostedimages.aweber-static.com/" />
BannerSnack.com.xml:		to="https://s3.amazonaws.com/files.bannersnack.com/" />
Bucket_Explorer.com.xml:		to="https://s3.amazonaws.com/coppermine.bucketexplorer.com/" />
Camelcamelcamel.xml:		to="https://s3.amazonaws.com/s3.$1/"/>
Captura-Group.xml:		to="https://s3.amazonaws.com/cdn.measuredvoice.com/"/>
Center-for-Responsive-Politics.xml:		to="https://s3.amazonaws.com/$1s.opensecrets.org/"/>
CEtrk.com.xml:		to="https://s3.amazonaws.com/trk.cetrk.com/" />
Cl.ly.xml:		to="https://s3.amazonaws.com/f.cl.ly/" />
Cloudera.com.xml:		to="https://s3.amazonaws.com/files.cloudera.com/" />
Cloud-Privacy.xml:		to="https://s3.amazonaws.com/files.cloudprivacy.net/" />
Compendium.xml:		to="https://s3.amazonaws.com/global.content.compendiumblog.com/" />
CSC.xml:		to="https://s3.amazonaws.com/assetsdev1.csc.com/" />
Ctrl_Alt_Del.xml:		to="https://s3.amazonaws.com/cdn.cad-comic.com/" />
DaWanda.xml:		to="https://dawandaimages.s3.amazonaws.com/" />
DealerTrend.com.xml:		to="https://s3.amazonaws.com/images.dealertrend.com/" />
Docstoc.xml:		to="https://s3.amazonaws.com/img.docstoc.com/"/>
DocumentCloud.xml:		to="https://s3.amazonaws.com/s3.documentcloud.org/" />
Edublogs.xml:		to="https://s3.amazonaws.com/files.campus.edublogs.org/" />
Enjin.xml:	<rule from="^http://(files|assets|images)\.enjin\.com/" to="https://s3.amazonaws.com/$1.enjin.com/" />
Ezaxess.com.xml:		to="https://s3.amazonaws.com/files.ezaxess.com/" />
FastSpring.xml:		to="https://s3.amazonaws.com/resource.fastspring.com/" />
FeedBlitz.xml:		to="https://s3.amazonaws.com/$1s.feedblitz.com/" />
Filemobile.xml:		to="https://s3.amazonaws.com/$1.filemobile.com/" />
Free_Press.xml:		to="https://s3.amazonaws.com/s3.freepress.net/" />
Freshdesk.xml:		to="https://s3.amazonaws.com/cdn.freshdesk.com/" />
General-Electric.xml:		to="https://s3.amazonaws.com/files.$1.geblogs.com/"/>
GetChute.xml:		to="https://s3.amazonaws.com/media.getchute.com/" />
Get.It.xml:		to="https://s3.amazonaws.com/detect.get.it/" />
Goodreads.xml:	<rule from="^http://photo\.goodreads\.com/" to="https://s3.amazonaws.com/photo.goodreads.com/"/>
highways.gov.uk.xml:		to="https://s3.amazonaws.com/$1.highways.gov.uk/" />
Idea_Stations.org.xml:		to="https://s3.amazonaws.com/cdn.ideastations.org/" />
IMshopping.com.xml:		to="https://s3.amazonaws.com/product-images.imshopping.com/" />
InfNX.xml:		to="https://s3.amazonaws.com/$1.infnx.com/"/>
Instaemail.net.xml:		to="https://s3.amazonaws.com/cdn.instaemail.net/" />
Instagr.am.xml:		to="https://s3.amazonaws.com/instagram-static/images/" />
Intuit.xml:		to="https://s3.amazonaws.com/media.turbotaxcpaselect.intuit.com/" />
Investing-Channel.xml:		to="https://s3.amazonaws.com/cdn.investingchannel.com/" />
IPR_Software.com.xml:		to="https://s3.amazonaws.com/cms.ipressroom.com/" />
Issuu_Aps.xml:		to="https://s3.amazonaws.com/$1.issuu.com/" />
Jamendo.xml:		to="https://s3.amazonaws.com/imgcdn.jamendo.com/" />
JanRain.xml:		to="https://s3.amazonaws.com/janrain.quilt/" />
JList.com.xml:		to="https://s3.amazonaws.com/images3.jlist.com/" />
Justia.xml:		to="https://s3.amazonaws.com/$1.justia.com/" />
KIXEYE.xml:		to="https://s3.amazonaws.com/cdn.casualcollective.com/" />
Lanyrd.xml:		to="https://s3.amazonaws.com/static.lanyrd.net/" />
Leanpub.com.xml:		to="https://s3.amazonaws.com/samples.leanpub.com/" />
lime-technology.com.xml:		to="https://s3.amazonaws.com/dnld.lime-technology.com/" />
Linksys.xml:		to="https://cache-www.linksys.com.s3.amazonaws.com/cache-www.linksys.com/" />
Long_Access.com.xml:		to="https://s3.amazonaws.com/the.longaccess.com/" />
Mashery.xml:		to="https://s3.amazonaws.com/content.developer.mashery.com/" />
MediaMatters.org.xml:		to="https://s3.amazonaws.com/s3.mediamatters.org/" />
MediaPost.xml:		to="https://s3.amazonaws.com/media.mediapost.com/" />
MIC-Gadget.xml:		to="https://s3.amazonaws.com/images.micgadget.com/" />
Minalyzer.com.xml:		to="https://s3.amazonaws.com/images.minalyzer.com/" />
MiniMundos_online.com.xml:		to="https://s3.amazonaws.com/content.minimundosonline.com/" />
MotherJones.com.xml:		to="https://mj$1$2.s3.amazonaws.com/" />
MoveOn.xml:		to="https://s3.amazonaws.com/s3.moveon.org/" />
MyFreeCopyright.com.xml:		to="https://myfreecopyright.s3.amazonaws.com/" />
NewsBlur.com.xml:			to="https://s3.amazonaws.com/$1.newsblur.com/"/>
News_Distribution_Network.xml:		to="https://s3.amazonaws.com/$1.newsinc.com/" />
newsela.com.xml:		to="https://newsela-test-files-f331e.s3.amazonaws.com/" />
NYTimes-Problematic.xml:		to="https://s3.amazonaws.com/pimage.timespeople.nytimes.com/" />
Onswipe.xml:		to="https://s3.amazonaws.com/cdn.onswipe.com/synapse/" />
Onswipe.xml:		to="https://s3.amazonaws.com/$1.onswipe.com/" />
OPML.xml:		to="https://s3.amazonaws.com/static.opml.org/" />
PBS.xml:		to="https://s3.amazonaws.com/pbs." />
Petridish.xml:		to="https://s3.amazonaws.com/media.petridish.org/"/>
Pivotal_Labs.xml:		to="https://s3.amazonaws.com/assets.pivotallabs.com/" />
Pixlr.xml:		to="https://s3.amazonaws.com/i.imm.io/" />
PR-Newswire.xml:		to="https://s3.amazonaws.com/filecache.drivetheweb.com/" />
Quizsnack.com.xml:		to="https://s3.amazonaws.com/files.quizsnack.com/" />
Quora.xml:		to="https://$1.s3.amazonaws.com/" />
RealClearPolitics.com.xml:		to="https://s3.amazonaws.com/assets.realclearpolitics.com/" />
Roster-Teeth.xml:		to="https://s3.amazonaws.com/s3.roosterteeth.com/" />
RPXNow.com.xml:		to="https://s3.amazonaws.com/static.rpxnow.com/" />
SBNdev.net.xml:		to="https://s3.amazonaws.com/share.sbndev.net/" />
Scribd.com.xml:		to="https://s3.amazonaws.com/img.scribd.com/" />
Scripting-News.xml:		to="https://s3.amazonaws.com/static.scripting.com/" />
Shacknews.xml:		to="https://shacknews.s3.amazonaws.com/" />
Sidearm_Sports.xml:		to="https://s3.amazonaws.com/assets.sidearmsports.com/" />
SideReel.xml:		to="https://s3.amazonaws.com/sidereel-production-static/" />
SideReel.xml:		to="https://sidereel-editorial.s3.amazonaws.com/" />
SlideMyPics.xml:		to="https://s3.amazonaws.com/files.slidemypics.com/" />
SMF_for_Free.xml:		to="https://s3.amazonaws.com/images.smfboards.com/" />
Smowtion.xml:		to="https://s3.amazonaws.com/px.smowtion.com/" />
Squarespace.xml:		to="https://s3.amazonaws.com/s3.media.squarespace.com/" />
stelladotcdn.com.xml:		to="https://s3.amazonaws.com/com.stelladot.static/" />
Sunlight-Foundation.xml:		to="https://s3.amazonaws.com/assets.sunlightfoundation.com/"/>
The_Patriot_Post.xml:		to="https://s3.amazonaws.com/$1/" />
Typotheque.xml:		to="https://tptqimages.s3.amazonaws.com/" />
Ubisoft-Entertainment.xml:		to="https://s3.amazonaws.com/static$1.ubi.com/" />
UniversalSubtitles.xml:	  to="https://s3.amazonaws.com/s3.www.universalsubtitles.org/" />
UN_Multimedia.org.xml:		to="https://s3.amazonaws.com/downloads.unmultimedia.org/" />
Vcommerce.xml:		to="https://s3.amazonaws.com/content.vcommerce.com/" />
Vitalwerks.xml:		to="https://noipcdn.s3.amazonaws.com/"/>
WhippleHill.xml:		to="https://s3.amazonaws.com/schoolpress.cdn.whipplehill.net/" />
Whiskey-Media.xml:		to="https://s3.amazonaws.com/media.$1.com/" />
Wishabi.xml:		to="https://s3.amazonaws.com/f.wishabi.ca/" />
Woot.xml:		to="https://s3.amazonaws.com/image.w00t.com/" />
Woot.xml:		to="https://s3.amazonaws.com/$1.woot.com/" />
WSJ.net.xml:		to="https://s3.amazonaws.com/images.conferences.wsj.net/" />
Youmix.xml:		to="https://s3.amazonaws.com/$1.youmix.co.uk/"/>
Yuku.xml:		to="https://s3.amazonaws.com/$1.yuku.com/" />
Zimbra.xml:		to="https://s3.amazonaws.com/files.zimbra.com/" />
```

**Comment by pipboy96** [comment]
Pinned since this affects many high-traffic websites and will cause breakage on them. If anyone thinks this should not be pinned, please tell me.

**Comment by zoracon** [comment]
@pipboy96 Pinning this is fine, it impacts quite a number of rulesets

**Comment by zoracon** [comment]
- [ ] 3D_Vision_Live.com.xml:		to="https://s3.amazonaws.com/photos.3dvisionlive/$2/images/$1/cached.thumb.square.208.208.0.0" /-->
- [ ] AboutUs.xml:		to="https://s3.amazonaws.com/au-site-static-assets/" />
- [ ] ActBlue.xml:		to="https://s3.amazonaws.com/i.actblue.com/" />
- [ ] AdExcite.xml:		to="https://adexcite.s3.amazonaws.com/" />
- [ ] AdExtent.com.xml:		to="https://s3.amazonaws.com/appv2.adextent.com/" />
- [ ] Adobe.xml:		to="https://s3.amazonaws.com/images.groups.adobe.com/" />
- [ ] Alonetone.xml:		to="https://s3.amazonaws.com/stash.alonetone.com/" />
- [ ] AmazonAWS.com.xml:		to="https://s3.amazonaws.com/static.newsblur.com/" />
- [ ] AmazonAWS.com.xml:		to="https://$1.s3.amazonaws.com/" /-->
- [ ] AmazonAWS.com.xml:		to="https://s3.amazonaws.com/$1.$2/" /-->
- [ ] AmazonAWS.com.xml:		to="https://s3.amazonaws.com/" />
- [ ] AWeber.xml:		to="https://s3.amazonaws.com/hostedimages.aweber-static.com/" />
- [ ] BannerSnack.com.xml:		to="https://s3.amazonaws.com/files.bannersnack.com/" />
- [ ] Bucket_Explorer.com.xml:		to="https://s3.amazonaws.com/coppermine.bucketexplorer.com/" />
- [ ] Camelcamelcamel.xml:		to="https://s3.amazonaws.com/s3.$1/"/>
- [ ] Captura-Group.xml:		to="https://s3.amazonaws.com/cdn.measuredvoice.com/"/>
- [ ] Center-for-Responsive-Politics.xml:		to="https://s3.amazonaws.com/$1s.opensecrets.org/"/>
- [ ] CEtrk.com.xml:		to="https://s3.amazonaws.com/trk.cetrk.com/" />
- [ ] Cl.ly.xml:		to="https://s3.amazonaws.com/f.cl.ly/" />
- [ ] Cloudera.com.xml:		to="https://s3.amazonaws.com/files.cloudera.com/" />
- [ ] Cloud-Privacy.xml:		to="https://s3.amazonaws.com/files.cloudprivacy.net/" />
- [ ] Compendium.xml:		to="https://s3.amazonaws.com/global.content.compendiumblog.com/" />
- [ ] CSC.xml:		to="https://s3.amazonaws.com/assetsdev1.csc.com/" />
- [ ] Ctrl_Alt_Del.xml:		to="https://s3.amazonaws.com/cdn.cad-comic.com/" />
- [ ] DaWanda.xml:		to="https://dawandaimages.s3.amazonaws.com/" />
- [ ] DealerTrend.com.xml:		to="https://s3.amazonaws.com/images.dealertrend.com/" />
- [ ] Docstoc.xml:		to="https://s3.amazonaws.com/img.docstoc.com/"/>
- [ ] DocumentCloud.xml:		to="https://s3.amazonaws.com/s3.documentcloud.org/" />
- [ ] Edublogs.xml:		to="https://s3.amazonaws.com/files.campus.edublogs.org/" />
- [ ] Enjin.xml:	<rule from="^http://(files|assets|images)\.enjin\.com/" to="https://s3.amazonaws.com/$1.enjin.com/" />
- [ ] Ezaxess.com.xml:		to="https://s3.amazonaws.com/files.ezaxess.com/" />
- [ ] FastSpring.xml:		to="https://s3.amazonaws.com/resource.fastspring.com/" />
- [ ] FeedBlitz.xml:		to="https://s3.amazonaws.com/$1s.feedblitz.com/" />
- [ ] Filemobile.xml:		to="https://s3.amazonaws.com/$1.filemobile.com/" />
- [ ] Free_Press.xml:		to="https://s3.amazonaws.com/s3.freepress.net/" />
- [ ] Freshdesk.xml:		to="https://s3.amazonaws.com/cdn.freshdesk.com/" />
- [ ] General-Electric.xml:		to="https://s3.amazonaws.com/files.$1.geblogs.com/"/>
- [ ] GetChute.xml:		to="https://s3.amazonaws.com/media.getchute.com/" />
- [ ] Get.It.xml:		to="https://s3.amazonaws.com/detect.get.it/" />
- [ ] Goodreads.xml:	<rule from="^http://photo\.goodreads\.com/" to="https://s3.amazonaws.com/photo.goodreads.com/"/>
- [ ] highways.gov.uk.xml:		to="https://s3.amazonaws.com/$1.highways.gov.uk/" />
- [ ] Idea_Stations.org.xml:		to="https://s3.amazonaws.com/cdn.ideastations.org/" />
- [ ] IMshopping.com.xml:		to="https://s3.amazonaws.com/product-images.imshopping.com/" />
- [ ] InfNX.xml:		to="https://s3.amazonaws.com/$1.infnx.com/"/>
- [ ] Instaemail.net.xml:		to="https://s3.amazonaws.com/cdn.instaemail.net/" />
- [ ] Instagr.am.xml:**		to="https://s3.amazonaws.com/instagram-static/images/" />
- [ ] Intuit.xml:		to="https://s3.amazonaws.com/media.turbotaxcpaselect.intuit.com/" />
- [ ] Investing-Channel.xml:		to="https://s3.amazonaws.com/cdn.investingchannel.com/" />
- [ ] IPR_Software.com.xml:		to="https://s3.amazonaws.com/cms.ipressroom.com/" />
- [ ] Issuu_Aps.xml:		to="https://s3.amazonaws.com/$1.issuu.com/" />
- [ ] Jamendo.xml:		to="https://s3.amazonaws.com/imgcdn.jamendo.com/" />
- [ ] JanRain.xml:		to="https://s3.amazonaws.com/janrain.quilt/" />
- [ ] JList.com.xml:		to="https://s3.amazonaws.com/images3.jlist.com/" />
- [ ] Justia.xml:		to="https://s3.amazonaws.com/$1.justia.com/" />
- [ ] KIXEYE.xml:		to="https://s3.amazonaws.com/cdn.casualcollective.com/" />
- [ ] Lanyrd.xml:		to="https://s3.amazonaws.com/static.lanyrd.net/" />
- [ ] Leanpub.com.xml:		to="https://s3.amazonaws.com/samples.leanpub.com/" />
- [ ] lime-technology.com.xml:		to="https://s3.amazonaws.com/dnld.lime-technology.com/" />
- [ ] Linksys.xml:		to="https://cache-www.linksys.com.s3.amazonaws.com/cache-www.linksys.com/" />
- [ ] Long_Access.com.xml:		to="https://s3.amazonaws.com/the.longaccess.com/" />
- [ ] Mashery.xml:		to="https://s3.amazonaws.com/content.developer.mashery.com/" />
- [ ] MediaMatters.org.xml:		to="https://s3.amazonaws.com/s3.mediamatters.org/" />
- [ ] MediaPost.xml:		to="https://s3.amazonaws.com/media.mediapost.com/" />
- [ ] MIC-Gadget.xml:		to="https://s3.amazonaws.com/images.micgadget.com/" />
- [ ] Minalyzer.com.xml:		to="https://s3.amazonaws.com/images.minalyzer.com/" />
- [ ] MiniMundos_online.com.xml:		to="https://s3.amazonaws.com/content.minimundosonline.com/" />
- [ ] MotherJones.com.xml:		to="https://mj$1$2.s3.amazonaws.com/" />
- [ ] MoveOn.xml:		to="https://s3.amazonaws.com/s3.moveon.org/" />
- [ ] MyFreeCopyright.com.xml:		to="https://myfreecopyright.s3.amazonaws.com/" />
- [ ] NewsBlur.com.xml:			to="https://s3.amazonaws.com/$1.newsblur.com/"/>
- [ ] News_Distribution_Network.xml:		to="https://s3.amazonaws.com/$1.newsinc.com/" />
- [ ] newsela.com.xml:		to="https://newsela-test-files-f331e.s3.amazonaws.com/" />
- [ ] NYTimes-Problematic.xml:		to="https://s3.amazonaws.com/pimage.timespeople.nytimes.com/" />
- [ ] Onswipe.xml:		to="https://s3.amazonaws.com/cdn.onswipe.com/synapse/" />, to="https://s3.amazonaws.com/$1.onswipe.com/" />
- [ ] OPML.xml:		to="https://s3.amazonaws.com/static.opml.org/" />
- [ ] PBS.xml:		to="https://s3.amazonaws.com/pbs." />
- [ ] Petridish.xml:		to="https://s3.amazonaws.com/media.petridish.org/"/>
- [ ] Pivotal_Labs.xml:		to="https://s3.amazonaws.com/assets.pivotallabs.com/" />
- [ ] Pixlr.xml:		to="https://s3.amazonaws.com/i.imm.io/" />
- [ ] PR-Newswire.xml:		to="https://s3.amazonaws.com/filecache.drivetheweb.com/" />
- [ ] Quizsnack.com.xml:		to="https://s3.amazonaws.com/files.quizsnack.com/" />
- [ ] Quora.xml:		to="https://$1.s3.amazonaws.com/" />
- [ ] RealClearPolitics.com.xml:		to="https://s3.amazonaws.com/assets.realclearpolitics.com/" />
- [ ] Roster-Teeth.xml:		to="https://s3.amazonaws.com/s3.roosterteeth.com/" />
- [ ] RPXNow.com.xml:		to="https://s3.amazonaws.com/static.rpxnow.com/" />
- [ ] SBNdev.net.xml:		to="https://s3.amazonaws.com/share.sbndev.net/" />
- [ ] Scribd.com.xml:		to="https://s3.amazonaws.com/img.scribd.com/" />
- [ ] Scripting-News.xml:		to="https://s3.amazonaws.com/static.scripting.com/" />
- [ ] Shacknews.xml:		to="https://shacknews.s3.amazonaws.com/" />
- [ ] Sidearm_Sports.xml:		to="https://s3.amazonaws.com/assets.sidearmsports.com/" />
- [ ] SideReel.xml:		to="https://s3.amazonaws.com/sidereel-production-static/" />
- [ ] SideReel.xml:		to="https://sidereel-editorial.s3.amazonaws.com/" />
- [ ] SlideMyPics.xml:		to="https://s3.amazonaws.com/files.slidemypics.com/" />
- [ ] SMF_for_Free.xml:		to="https://s3.amazonaws.com/images.smfboards.com/" />
- [ ] Smowtion.xml:		to="https://s3.amazonaws.com/px.smowtion.com/" />
- [ ] Squarespace.xml:		to="https://s3.amazonaws.com/s3.media.squarespace.com/" />
- [ ] stelladotcdn.com.xml:		to="https://s3.amazonaws.com/com.stelladot.static/" />
- [ ] Sunlight-Foundation.xml:		to="https://s3.amazonaws.com/assets.sunlightfoundation.com/"/>
- [ ] The_Patriot_Post.xml:		to="https://s3.amazonaws.com/$1/" />
- [ ] Typotheque.xml:		to="https://tptqimages.s3.amazonaws.com/" />
- [ ] Ubisoft-Entertainment.xml:		to="https://s3.amazonaws.com/static$1.ubi.com/" />
- [ ] UniversalSubtitles.xml:	  to="https://s3.amazonaws.com/s3.www.universalsubtitles.org/" />
- [ ] UN_Multimedia.org.xml:		to="https://s3.amazonaws.com/downloads.unmultimedia.org/" />
- [ ] Vcommerce.xml:		to="https://s3.amazonaws.com/content.vcommerce.com/" />
- [ ] Vitalwerks.xml:		to="https://noipcdn.s3.amazonaws.com/"/>
- [ ] WhippleHill.xml:		to="https://s3.amazonaws.com/schoolpress.cdn.whipplehill.net/" />
- [ ] Whiskey-Media.xml:		to="https://s3.amazonaws.com/media.$1.com/" />
- [ ] Wishabi.xml:		to="https://s3.amazonaws.com/f.wishabi.ca/" />
- [ ] Woot.xml:		to="https://s3.amazonaws.com/image.w00t.com/" />
- [ ] Woot.xml:		to="https://s3.amazonaws.com/$1.woot.com/" />
- [ ] WSJ.net.xml:		to="https://s3.amazonaws.com/images.conferences.wsj.net/" />
- [ ] Youmix.xml:		to="https://s3.amazonaws.com/$1.youmix.co.uk/"/>
- [ ] Yuku.xml:		to="https://s3.amazonaws.com/$1.yuku.com/" />
- [ ] Zimbra.xml:		to="https://s3.amazonaws.com/files.zimbra.com/" />

**Comment by cschanaj** [comment]
#17912 fixed `stelladotcdn.com.xml`

**Comment by zoracon** [comment]
When resolved, closes #2709

**Comment by zoracon** [comment]
When resolved: closes #17717

**Comment by pipboy96** [comment]
@zoracon Only two days remain, can you merge the remaining PRs and make a ruleset release?

**Comment by jsha** [comment]
FYI there's an update on the linked post, which I think makes this less urgent: https://forums.aws.amazon.com/ann.jspa?annID=6776

> Updated on September 23, 2020
> Over the last year, we’ve heard feedback from many customers who have asked us to extend the deprecation date of path-style URLs. Based on this feedback, we have decided to delay the deprecation of path-style URLs to ensure that customers have the time that they need to transition to virtual hosted-style URLs.

**Comment by pipboy96** [comment]
@jsha That's nice. Do you know when will existing path-style URLs stop working (the post you linked to says that there will be at least one year until path-style URLs will stop working for new buckets)?

**Comment by zoracon** [comment]
Taking the time to power through the rest of these today and tomorrow.

**Comment by cschanaj** [comment]
@zoracon #19628 #19629 #19630 #19631 are ready for reviews.

**Comment by zoracon** [comment]
Released updated rulesets! Thank you everyone for the hard work!
