### ISSUE TITLE
Fix rulesets with problematic targets/ rewrites 

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#17965]
The following problematic rulesets contain either unprotected targets/ invalid rewrites found using the script in #17855. These should be fixed if possible.

- [ ] Academia-Press.xml
- [ ] AEMI.xml
- [ ] Alluremedia.xml
- [ ] Argus_Leader.xml
- [ ] ARM.xml
- [ ] Axis_Bank.xml
- [ ] Branson_Zipline.xml
- [ ] BT_Wi-fi.xml
- [ ] Clicksor.com.xml
- [ ] Commission_Junction.xml
- [ ] Coupons-Inc.xml
- [ ] Demand-Media-mismatches.xml
- [ ] Dial_Direct.xml
- [ ] Digiweb.xml
- [ ] DuckCorp.xml
- [ ] E-junkie.xml
- [ ] EmuNewz-Network.xml
- [ ] Entertainment-Consumers-Association.xml
- [ ] Erowid.xml
- [ ] Experian.xml
- [ ] EZTV.xml
- [ ] Factory_Expo_Home_Centers.xml
- [ ] FierceMarkets.xml
- [ ] Flaska.net.xml
- [ ] Florida_Today.xml #17906 
- [ ] FlyersRights.org.xml #17904 
- [ ] FOX-Toolkit.xml
- [ ] Fujitsu.xml
- [ ] Globat.xml
- [ ] Goldkeys.net.xml
- [ ] GTCs-Online.xml
- [ ] gulli.com.xml
- [ ] Halifax.xml
- [ ] Herdict.xml
- [ ] Hi.nl.xml
- [ ] Holidaybreak.xml
- [ ] HurricaneElectric.xml
- [ ] Indiana_State_University.xml #17887 
- [ ] Infused-Systems-mismatches.xml
- [ ] ION-Audio.xml
- [ ] Lohud.com.xml
- [ ] MediaMind.xml
- [ ] MediaSpan.xml
- [ ] Media-Storehouse.xml
- [ ] Monkeys-Audio.xml
- [ ] MSN-mismatches.xml
- [ ] MyLikes.xml
- [ ] NewspaperDirect-mismatches.xml
- [ ] Nowy_BIP.xml
- [ ] NPR.org.xml
- [ ] Online.nl.xml
- [ ] OU.edu.xml
- [ ] Overclockers.com.xml
- [ ] Patriotsuperbowl.us.xml
- [ ] PBwiki.xml
- [ ] Pearson.xml
- [ ] Peer1.ca.xml
- [ ] RapidBuyr.xml
- [ ] RedIRIS.es.xml
- [ ] Sears.com.xml
- [ ] SemiAccurate.xml
- [ ] ShopWiki.xml
- [ ] Sinica.edu.tw.xml
- [ ] Starwood-Hotels-and-Resorts.xml
- [ ] Umea_University.xml
- [ ] Uni.Lu.xml #17964 
- [ ] University_of_Houston.xml
- [ ] ValueClick.xml
- [ ] v.gd.xml
- [ ] Vispa.xml
- [ ] WebMD.xml
- [ ] West_Virginia_University-problematic.xml

```
[WARN] AEMI.xml: ruleset contains targets aemi.edu.au not applied to any rewrites
[WARN] ARM.xml: ruleset rewrites domains arm.com unsupported by *.arm.com
[WARN] Academia-Press.xml: ruleset contains targets *.www.academiapress.be not applied to any rewrites
[WARN] Alluremedia.xml: ruleset rewrites domains edge.alluremedia.com unsupported by *.alluremedia.com.au
[WARN] Argus_Leader.xml: ruleset contains targets argusleader.com not applied to any rewrites
[WARN] Axis_Bank.xml: ruleset rewrites domains axisbank.co.in unsupported by www.axisbank.co.in, axisbank.com, *.axisbank.com
[WARN] BT_Wi-fi.xml: ruleset rewrites domains my.btwifi.co.uk unsupported by btwifi.co.uk, www.btwifi.co.uk, btwifi.com, *.btwifi.com
[WARN] Branson_Zipline.xml: ruleset rewrites domains css.bzimages.com unsupported by bransonzipline.com, *.bransonzipline.com, img.bzimages.com
[WARN] Clicksor.com.xml: ruleset rewrites domains pub.clicksor.net unsupported by *.clicksor.com
[WARN] Commission_Junction.xml: ruleset rewrites domains www.afcyhf.net unsupported by www.afcyhf.com, www.anrdoezrs.net, www.apmebf.com, www.awltovhc.com, www.awxibrm.com, cj.com, *.cj.com, www.commission-junction.com, www.cualbr.com, www.dpbolvw.net, www.emjcd.com, www.ftjcfx.com, www.jdoqocy.com, www.kdukvh.com, www.kqzyfj.com, www.pkracv.com, www.rnsfpw.net, www.qksrv.net, www.qksz.net, www.tkqlhce.com, www.tqlkg.com, www.vofzpwh.com, www.yceml.net
[WARN] Coupons-Inc.xml: ruleset rewrites domains coupouns.com unsupported by coupons.com, *.coupons.com, cdn.cpnscdn.com
[WARN] Demand-Media-mismatches.xml: ruleset contains targets photos2.demandmedia.com not applied to any rewrites
[WARN] Dial_Direct.xml: ruleset contains targets *.www.dialdirect.co.uk not applied to any rewrites
[WARN] Digiweb.xml: ruleset rewrites domains novera.ie unsupported by manage.hosting.digiweb.ie, secureorders.digiweb.ie, host.ie, *.host.ie, novara.ie, www.novara.ie, ncm.novarait.com, promote.ie, www.promote.ie, register.ie, www.register.ie
[WARN] DuckCorp.xml: ruleset contains targets mini-dweeb.org not applied to any rewrites
[WARN] E-junkie.xml: ruleset rewrites domains ejunkie.com unsupported by e-junkie.com, *.e-junkie.com
[WARN] EZTV.xml: ruleset rewrites domains torrent.zoink.it unsupported by ezimg.it, *.ezimg.it, ezrss.it, www.ezrss.it, eztv.it, *.eztv.it, zoink.it, www.zoink.it
[WARN] EmuNewz-Network.xml: ruleset contains targets *.www.emunews.net not applied to any rewrites
[WARN] Entertainment-Consumers-Association.xml: ruleset contains targets theeca.com not applied to any rewrites
[WARN] Erowid.xml: ruleset contains targets *.www.erowid.org not applied to any rewrites
[WARN] Experian.xml: ruleset contains targets *.experian.experiandirect.com not applied to any rewrites
[WARN] FOX-Toolkit.xml: ruleset contains targets fox-toolkit.net, fox-toolkit.org not applied to any rewrites
[WARN] Factory_Expo_Home_Centers.xml: ruleset rewrites domains factoryexpoexpohomes.com unsupported by azchampion.com, *.azchampion.com, cimacorp.net, www.cimacorp.net, expohomes.com, *.expohomes.com, expomobilehomes.com, *.expomobilehomes.com, factorydirectcabins.com, *.factorydirectcabins.com, factoryexpo.net, *.factoryexpo.net, factoryexpodirect.com, *.factoryexpodirect.com, factoryexpohomes.com, *.factoryexpohomes.com, factoryhomesale.com, www.factoryhomesale.com, factoryselecthomes.com, *.factoryselecthomes.com, fbhexpo.com, *.fbhexpo.com
[WARN] FierceMarkets.xml: ruleset contains targets assets.fiercemarkets.net not applied to any rewrites
[WARN] Flaska.net.xml: ruleset rewrites domains flaska.net unsupported by *.flaska.net
[WARN] Florida_Today.xml: ruleset rewrites domains ads.flatdy.net unsupported by ads.flatdy.com, floridatoday.com, *.floridatoday.com
[WARN] FlyersRights.org.xml: ruleset rewrites domains anything.flyersrights.org unsupported by flyersrights.com, *.flyersrights.com, flyersrights.org, www.flyersrights.org
[WARN] Fujitsu.xml: ruleset contains targets *.www.fujitsu-webmart.com not applied to any rewrites
[WARN] GTCs-Online.xml: ruleset contains targets *.gtcsonline.mycashflow.fi, peliaika.fi not applied to any rewrites
[WARN] Globat.xml: ruleset rewrites domains globat.com443 unsupported by globat.com, *.globat.com
[WARN] Goldkeys.net.xml: ruleset rewrites domains www.goldkeys.org unsupported by *.goldkeys.net, portal.goldkeys.org
[WARN] Halifax.xml: ruleset rewrites domains halifax-online.co.uk unsupported by halifax.co.uk, *.halifax.co.uk, *.halifax-online.co.uk
[WARN] Herdict.xml: ruleset rewrites domains nardikt.org unsupported by herdict.org, *.herdict.org, nardikt.ru, *.nardikt.ru
[WARN] Hi.nl.xml: ruleset rewrites domains hi.nl unsupported by *.hi.nl
[WARN] Holidaybreak.xml: ruleset rewrites domains pgl.co.uk unsupported by djoserjunior.nl, www.djoserjunior.nl, djoserwandelenfiets.nl, www.djoserwandelenfiets.nl, holidaybreak.co.uk, www.holidaybreak.co.uk, *.superbreak.net
[WARN] ION-Audio.xml: ruleset contains targets *.www.ionaudio.com not applied to any rewrites
[WARN] Indiana_State_University.xml: ruleset rewrites domains indstate.edu unsupported by *.indstate.edu
[WARN] Infused-Systems-mismatches.xml: ruleset rewrites domains cdn.infusionsoft.com unsupported by *.insft.com, infusedsystems.com, *.infusedsystems.com
[WARN] HurricaneElectric.xml: ruleset rewrites domains www.hurricaneelectric.net unsupported by he.com, www.he.com, he.net, *.he.net, hurricaneelectric.net
[WARN] Lohud.com.xml: ruleset contains targets thejournalnews.com, *.thejournalnews.com not applied to any rewrites
[WARN] MSN-mismatches.xml: ruleset rewrites domains allday.today.msnbc.com unsupported by msnbc.msn.com, msndata.jp.msn.com, *.msnbc.msn.com, my.msn.com, eb.my.msn.com, m.now.msn.com, realestate.msn.com, wonderwall.msn.com, img1.video.s-msn.com
[WARN] Media-Storehouse.xml: ruleset contains targets mediastorehouse.com not applied to any rewrites
[WARN] MediaMind.xml: ruleset rewrites domains eyeblasterwiz.com unsupported by *.mediamind.com, a.pgtb.me
[WARN] MediaSpan.xml: ruleset rewrites domains assets.fimc.net unsupported by fimc.net, www.fimc.net, mediaspanonline.com, *.mediaspanonline.com
[WARN] Monkeys-Audio.xml: ruleset contains targets monkeysaudio.com not applied to any rewrites
[WARN] MyLikes.xml: ruleset contains targets *.longurl.it not applied to any rewrites
[WARN] NPR.org.xml: ruleset rewrites domains support.kunc.org unsupported by kunk.org, *.kunk.org, npr.org, *.npr.org
[WARN] NewspaperDirect-mismatches.xml: ruleset contains targets pressdisplay.com not applied to any rewrites
[WARN] Nowy_BIP.xml: ruleset contains targets nowybip.siteor.com not applied to any rewrites
[WARN] OU.edu.xml: ruleset rewrites domains ou.edu unsupported by *.ou.edu
[WARN] Online.nl.xml: ruleset rewrites domains online.nl unsupported by *.online.nl
[WARN] Overclockers.com.xml: ruleset contains targets ocforums.com not applied to any rewrites
[WARN] PBwiki.xml: ruleset rewrites domains files.pbworks.com unsupported by *.pbwiki.com
[WARN] Patriotsuperbowl.us.xml: ruleset contains targets *.www.patriotssuperbowl.us not applied to any rewrites
[WARN] Pearson.xml: ruleset rewrites domains www8.vue.com unsupported by *.pearson.com, register.pearsoncmg.com, pearsonvue.com, *.pearsonvue.com, vue.com, www.vue.com
[WARN] Peer1.ca.xml: ruleset rewrites domains partners.peer1.ca unsupported by *.peer1.com
[WARN] RapidBuyr.xml: ruleset contains targets rapidbuyr.cachefly.net not applied to any rewrites
[WARN] RedIRIS.es.xml: ruleset rewrites domains rediris.net unsupported by pki.irisgrid.es, rediris.es, *.rediris.es, www.rediris.net
[WARN] Sears.com.xml: ruleset rewrites domains sears.com unsupported by *.sears.com
[WARN] SemiAccurate.xml: ruleset rewrites domains stonearch.net unsupported by semiaccurate.com, *.semiaccurate.com, www.stonearch.net
[WARN] ShopWiki.xml: ruleset rewrites domains s.shwcd.com unsupported by shopwiki.com, *.shopwiki.com
[WARN] Sinica.edu.tw.xml: ruleset rewrites domains ascc.sinica.edu unsupported by *.sinica.edu.tw
[WARN] Starwood-Hotels-and-Resorts.xml: ruleset contains targets *.www.starwoodhotels.com not applied to any rewrites
[WARN] Umea_University.xml: ruleset rewrites domains www.cambroumu.se unsupported by umu.se, *.umu.se
[WARN] Uni.Lu.xml: ruleset rewrites domains hpc.uni.lu unsupported by *.uni.lui
[WARN] University_of_Houston.xml: ruleset rewrites domains uh.edu unsupported by *.uh.edu
[WARN] ValueClick.xml: ruleset rewrites domains fastclickmedia.com unsupported by *.apmebf.com, fastclick.com, www.fastclick.com, *.fastclick.net, mediaplex.com, *.mediaplex.com, *.mplxtms.com, valueclick.com, www.valueclick.com, valueclickmedia.com, *.valueclickmedia.com
[WARN] Vispa.xml: ruleset contains targets *.www.vispashop.com not applied to any rewrites
[WARN] WebMD.xml: ruleset rewrites domains ls.turn.com unsupported by *.webmd.com
[WARN] West_Virginia_University-problematic.xml: ruleset rewrites domains oric.research.wvu.edu unsupported by beta.campusmap.wvu.edu, *.hr.wvu.edu, simpleforms.scripts.wvu.edu, *.slate.wvu.edu, *.ur.wvu.edu
[WARN] gulli.com.xml: ruleset contains targets gullipics.com, *.gullipics.com not applied to any rewrites
[WARN] v.gd.xml: ruleset contains targets *.v.gd not applied to any rewrites
```

**Comment by pipboy96** [comment]
@zoracon If you feel pin is inappropriate, please unpin.
