### ISSUE TITLE
Audit default_off rulesets

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#9842]
Type: ruleset issue

Domain: *

Similar to #9582, I suspect 168 out of 537 `default_off="self-signed"` rulesets can be re-activated. I added a date to PRs which haven't been merge after being reviewed for a long time.

### Self-signed

 - [ ] 112cafe.com
 - [x] www.aaai.org #9824 
 - [x] connect.aber.ac.uk #10116 
 - [x] airs.com #9815 
 - [x] all-about-security.de #11087 
 - [x] alltop.com #9862 
 - [x] www.anarchistnews.org #9409 `(4 Apr 2017)`
 - [ ] ancud.de
 - [x] atomicinsights.com #10194 
 - [x] av-comparatives.org #10407 
 - [ ] badgeville.com
 - [x] crosswire.org #9845 
 - [ ] bartleby.com
 - [ ] store.fileforum.com
 - [x] bioinfobank.com #9853 
 - [x] bioinfo.pl #9853
 - [ ] vz46.brenet.de
 - [x] b-link.bucknell.edu #10083 
 - [x] alumni.buffalostate.edu  #10121 
 - [x] cn.calameo.com #9869 
 - [ ] channeladvisor.com
 - [x] members.chicagotribune.com #10068 
 - [x] coinjabber.com #9872 
 - [ ] allure.com
 - [x] couragecampaign.org #9858 
 - [ ] creativevirtual.com
 - [x] darkreading.com #9952 
 - [x] dealzon.com #11086 
 - [x] dave.org.uk #9907 
 - [ ] denx.de
 - [x] devconf.cz #9951
 - [ ] digitalmars.com
 - [x] diygadget.com #10105 
 - [ ] dlisted.com
 - [ ] drwho.virtadpt.net
 - [x] global.duke.edu #10102 
 - [ ] echothrust.com
 - [ ] egyptindependent.com
 - [ ] energylivenews.com
 - [ ] engelschall.com
 - [ ] esportsea.com
 - [x] europe-consommateurs.eu #9855 
 - [x] evoliatis.com #10103 
 - [ ] exiledonline.com
 - [x] fdopk.org #10118 
 - [ ] files.poulsander.com
 - [x] g10code.com #10015 
 - [x] fotoforensics.com #9954 
 - [x] downloads.rc.fas.harvard.edu #9878 
 - [ ] hiig.de
 - [ ] how-to-box.com
 - [ ] huxo.co.uk
 - [ ] best-pariuri-online.com
 - [ ] ihub.co.ke
 - [ ] imgdino.com
 - [x] imperialcollegeunion.org #9870 
 - [x] gentoo.ussg.indiana.edu #10075 
 - [ ] infile.com
 - [ ] inphi.com
 - [x] ircreviews.org #9860 
 - [ ] iwmnetwork.com
 - [ ] jeja.pl
 - [ ] jguitar.com
 - [ ] joomlancers.com
 - [x] jpgmag.com #9873 
 - [ ] kenshoo.com
 - [ ] blog.kapsobor.de
 - [x] blog.bibliothek.kit.edu #10117 
 - [ ] katzporn.in (NSFW)
 - [ ] kosimak.com (NSFW)
 - [x] krautchan.net #6850 `(12 Sep 2016)`
 - [ ] linkomanija.net
 - [ ] mediacru.sh (`Deceptive site ahead` warning from `Google Safe Browsing`)
 - [ ] mediatakeout.com
 - [ ] megastock.ru
 - [x] mercatus.org #10192 
 - [x] mersenne.org #9843 
 - [ ] milwaukeemakerspace.org
 - [x] mirt.net #10230 
 - [ ] misadventureswithandi.com
 - [ ] mobileenterprise360.com
 - [x] movim.eu #9849 
 - [x] mpagano.com #10104 
 - [x] msfn.org #9854 
 - [ ] piwik.mutantbrains.com
 - [x] dev.mutt.org #9844 
 - [x] netveano.com #10109 
 - [ ] networkcomputing.com
 - [x] northdevontheatres.org.uk #10206 
 - [x] offog.org #9865 
 - [x] openwebmail.org #9822 
 - [ ] www.palmcoastdata.com
 - [x] patternsinthevoid.net #10014 
 - [ ] pcs.com
 - [ ] deutsch.peerius.com
 - [x] picostocks.com #9853 
 - [ ] piraten-mfr.de
 - [ ] fckme.org (NSFW)
 - [ ] pocketmatrix.com
 - [ ] praegnanz.de
 - [ ] premiertaxfree.com
 - [x] qupzilla.com #10111 
 - [x] racjonalista.pl #11089 
 - [ ] rage3d.com
 - [x] rdot.org #10195 
 - [x] informabtl.com #10207 
 - [x] ~resonant.org~ https://github.com/EFForg/https-everywhere/issues/9842#issuecomment-305725784
 - [ ] sb-innovation.de
 - [ ] pentacon.de
 - [x] scribus.net #9868 
 - [x] sebastianwick.net #11088 
 - [x] selectricity.org #9864 
 - [x] sharethefiles.com #9833 
 - [x] sheppyware.net #10108 
 - [x] sidux-ev.org #10119 
 - [ ] slipfire.com
 - [ ] smashfly.com
 - [x] springfiles.com #10204 
 - [ ] www.sraoss.co.jp
 - [ ] suburban.nl
 - [ ] susyradio.com
 - [ ] sweetslyrics.com
 - [x] systemed.net #10106 
 - [ ] t3blog.com
 - [ ] talkactive.net
 - [x] technoratimedia.com #10203 
 - [x] tinydl.com #9874 
 - [ ] tpg.com
 - [x] blog.tropo.com #9863 
 - [ ] tv-release.net
 - [ ] tweegy.nl
 - [x] uformia.com #10208 
 - [x] uglymugs.ie #10191 
 - [ ] ucw.cz
 - [ ] universe2.us
 - [x] astro.uchicago.edu #10077 
 - [x] fex.rus.uni-stuttgart.de #10100 
 - [x] seclab.cs.washington.edu #10101 
 - [ ] unvanquished.net
 - [x] hpcf.upr.edu #10054 
 - [ ] upxth.com (NSFW)
 - [x] vegasinc.com #9950 
 - [ ] vehiclevisuals.com
 - [ ] weburbanist.com
 - [x] mytaxandbenefits.wyreforestdc.gov.uk #10084 

#### HSTS
`Qualified but not preloaded`

 - [x] tr0n.net

#### HSTS Preloaded 

 - [x] aeon.co #9857, https://github.com/EFForg/https-everywhere/issues/9621#issuecomment-300029596

#### HSTS 
`Strict-Transport-Security: max-age >= 10886400; includeSubDomains`

 - [x] abma.de #10019 
 - [ ] anders.com 
 - [x] axelsimon.net #10193 
 - [x] bel.fi #10196 
 - [x] docs.cs.cf.ac.uk #10074 
 - [ ] datapipe.cn
 - [x] forum.doom9.org #9852 
 - [ ] contributors.gettyimages.com
 - [x] www.ginac.de #10048 
 - [ ] courtesan.com
 - [x] hackerspaces.org #10047 
 - [x] hacklab.to #10110 
 - [ ] kfwebs.net
 - [ ] kovidgoyal.net
 - [ ] merca20.com
 - [x] oscommerce.com #10850 
 - [ ] pearsoncomputing.net
 - [x] waste.org #10055 
 - [x] tibeti.xfce.org #9832 
 - [x] yabause.org #9846 

#### HSTS 
`Strict-Transport-Security: max-age < 10886400; includeSubDomains`
 - [x] logilab.org #8986
 - [ ] gnd-tech.com

### local issuser certificates

- [x] ~accan.org.au~
- [x] ~adxpansion.com~
- [x] ~alias.io~
- [x] ~alliedmedia.org~
- [x] charities.org #10088 
- [x] ~anb.com.sa~
- [x] ~atipso.com~
- [x] ~auctionthing.net~
- [x] ~hydra.aufbix.org~
- [x] savethekoala.com #10237 
- [ ] secure.avahost.net
- [ ] www.avropa.se
- [ ] brenet.de
- [ ] lung.ca
- [ ] canaldigital.dk
- [ ] capitolmachine.com
- [ ] chipworks.com
- [ ] webmail.bln.de.clara.net
- [ ] cloudscaling.com
- [x] projects.coin-or.org #10384 
- [x] ~secure.prleap.com~
- [ ] consumerswin.com
- [ ] coolkeywest.com
- [ ] cruisersforum.com
- [ ] cts-strasbourg.eu
- [ ] cvut.cz
- [ ] datacell.com
- [x] ~www.datatilsynet.no~
- [ ] depfile.com
- [ ] desire2learn.com
- [ ] dittdistrikt.no
- [ ] domaincamp.de
- [ ] duracellcloud.com
- [x] ~global.ebsco-content.com~
- [ ] e-estonia.com
- [ ] equinix.com
- [ ] esomar.org
- [x] ~admin.exmasters.com~
- [x] ~ehostpros.com~
- [ ] fromorbit.com
- [ ] gsn.com
- [ ] geoamigo.com
- [ ] givingprograms.com
- [ ] greatnet.de
- [ ] grouplogic.com
- [ ] hackerrank.com
- [ ] checksconnect.com
- [ ] hartvoorinternetvrijheid.nl
- [ ] headstrong.de
- [ ] www.hgo.se
- [ ] ihgmerlin.com
- [ ] crcpress.com
- [ ] ims-dm.com
- [ ] interlan.se
- [ ] my.ispsystem.com
- [ ] images.jxt.net.au
- [ ] www.kabelkiosk.de
- [ ] ksh.hu
- [ ] laptop.hu
- [x] linguee.com #10364 
- [ ] magazinesdirect.com
- [ ] services-sj.mediuscorp.com
- [ ] meego.com
- [ ] mentoringcentral.net
- [x] midnight-commander.org #10239 
- [ ] gomoxie.com
- [x] ~mozy.com~
- [ ] hds.nerc.ac.uk
- [x] naughtydog.com #10383 
- [ ] nydailynews.com
- [x] oppo.com #10266 
- [ ] outernet.is
- [x] ~pacebus.com~
- [x] ~packetwerk.com~
- [x] ~catalog.plsinfo.org~
- [x] ~cdn.assets-phoenix.net~
- [x] ~photonconsulting.com~
- [x] pingability.com #10238 
- [x] ~placeimg.com~
- [x] planet-source-code.com #10381 
- [x] ~powerspeaking.com~
- [x] ~reformal.ru~
- [x] ~relate.org.uk~
- [x] ~rfparts.com~
- [x] ~forums.sabnzbd.org~
- [x] ~sandsmedia.com~
- [x] ~sfm-offshore.com~
- [x] ~shoplocal.com~
- [x] ~simplebooklet.com~
- [x] ~siteblindado.com~
- [x] ~socialtheater.com~
- [x] techmeme.com #10271 
- [x] ~tehconnection.eu~
- [x] ~tendatta.com~
- [x] terragalleria.com #10380
- [x] terrapass.com #10379 
- [ ] prospect.org
- [x] bookdepository.co.uk #10240 
- [x] threatmetrix.com #10241
- [x] ~broadcaster.email-tickets.com~
- [x] ~easyedi.tietoenator.com~
- [x] ~tinychat.com~
- [x] tribler.org #10382 
- [ ] apol-recruit.ucsd.edu
- [x] ~ufies.org~
- [ ] unclineberger.org
- [x] ~rug.nl~
- [x] ~www.strath.ac.uk~
- [x] utk.edu #10275 
- [ ] www.ebenefits.va.gov
- [x] ~uwinnipeg.ca~
- [x] vault.cca.edu #10264 
- [ ] visionairlines.com
- [ ] secure.vispa.net.uk
- [x] ~vr.se~
- [x] ~moneyandmarkets.com~
- [x] winzip.com #10265

**Comment by Bisaloo** [comment]
https://github.com/EFForg/https-everywhere/pull/9409

**Comment by Bisaloo** [comment]
For your script, you should note that sometimes several reasons are listed for `default_off`. Do you currently catch such rulesets?

For example, [`WorkWithColor.xml`](https://www.eff.org/https-everywhere/atlas/domains/workwithcolor.com.html) (although it is maybe not the best example as it is still broken but you get the idea.

**Comment by cschanaj** [comment]
@Bisaloo You are right, the same hold true for #9582.  The script I use now only check if `default_off="self-signed"` is a full-match. 

I can make a generic script such that it works when we would like to audit on `mismatch`, `cacert`, `self-signed` etc (maybe tonight).

**Comment by cschanaj** [comment]
You can now refer to the newly created script on [GIST](https://gist.github.com/cschanaj/3223d286d7cee4a5b67aefd0b0df9b61). (Performance-wise I believe it can be further optimized). To use the script, you need to set the `KEYWORD` variable, for example
```
$ export KEYWORD="self-signed"
$ ./audit.sh
```

P.S. I will update the above list accordingly.

**Comment by Bisaloo** [comment]
I'd argue that `resonant.org` is still self-signed:

- https://resonant.org is valid but only content is the self-signed CA
- https://www.resonant.org is self-signed
- https://wiki.resonant.org is self-signed

**Comment by cschanaj** [comment]
@Bisaloo I agree that `resonant.org` is still self-signed. Updated the list accordingly, thanks a lot!!

**Comment by Bisaloo** [comment]
I found 118 additional domains with your script by running grep with `(60, 'SSL certificate problem: unable to get local issuer certificate')`.

Should I add them to this list or open a different issue? It's likely that among those 118 domains, not all of them were disabled due to being self-signed but also because of chain issues or the use of alternative authorities like CAcert.

**Comment by cschanaj** [comment]
@Bisaloo Please feel free to add them to this PR if you want, I do not mind updating the checklist for this. Thanks!!

**Comment by Bisaloo** [comment]
Great! The list is [here](https://raw.githubusercontent.com/Bisaloo/https-memo/2d8be6b7b6ce7a693d733739b2e5a233f4d4cb2c/fixed_cert_issues.txt) (or you can copy it directly with the checkboxes [here](https://raw.githubusercontent.com/Bisaloo/https-memo/master/fixed_cert_issues.txt).

**Comment by J0WI** [comment]
Can we close this in favor of smaller issues (e.g. #13290, #13176, #13088)?

**Comment by cschanaj** [comment]
@J0WI I agree. let's close this in favor of small issues :smile:
